remove tests that depend on un-exported types
    === RUN   TestDisablePigz
    --- FAIL: TestDisablePigz (0.00s)
    panic: interface conversion: io.Reader is *archive.readCloserWrapper, not *archive.readCloserWrapper (types from different packages) [recovered]

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>